.TH "src/Field.h" 3 "Version 0.0.1" "tic_tac_toe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Field.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBField\fP"
.br
.RI "represent game \fBField\fP\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBAddedResult\fP { \fBSUCCESS\fP, \fBFAIL\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBAddedResult\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISUCCESS \fP\fP
.TP
\fB\fIFAIL \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for tic_tac_toe from the source code\&.
