.TH "src/tic_tac_toe.cpp" 3 "Version 0.0.1" "tic_tac_toe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tic_tac_toe.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <windows\&.h>\fP
.br
\fC#include <random>\fP
.br
\fC#include 'Field\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBclear_screen\fP (const char fill=' ')"
.br
.ti -1c
.RI "void \fBai_turn\fP (const int field_width, \fBField\fP &field)"
.br
.ti -1c
.RI "void \fBplayer_turn\fP (\fBField\fP &field)"
.br
.ti -1c
.RI "void \fBtick\fP (\fBField\fP &field)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ai_turn (const int field_width, \fBField\fP & field)"

.SS "void clear_screen (const char fill = \fC' '\fP)"

.SS "int main ()"

.SS "void player_turn (\fBField\fP & field)"

.SS "void tick (\fBField\fP & field)"

.SH "Author"
.PP 
Generated automatically by Doxygen for tic_tac_toe from the source code\&.
