.TH "src/VectorExtensions.h" 3 "Version 0.0.1" "tic_tac_toe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/VectorExtensions.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVectorExtensions\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tic_tac_toe from the source code\&.
