.TH "VectorExtensions" 3 "Version 0.0.1" "tic_tac_toe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VectorExtensions
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VectorExtensions\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBjoin\fP (const std::vector< char > &vec, char delimiter, bool with_whitespace=true)"
.br
.RI "joins all vector chars into single string with delimiter\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::string VectorExtensions::join (const std::vector< char > & vec, char delimiter, bool with_whitespace = \fCtrue\fP)\fC [static]\fP"

.PP
joins all vector chars into single string with delimiter\&. 
.PP
\fBParameters\fP
.RS 4
\fIvec\fP vector of chars\&. 
.br
\fIdelimiter\fP delimiter char\&. 
.br
\fIwith_whitespace\fP should insert whitespace before element and after\&. 
.RE
.PP
\fBReturns\fP
.RS 4
string\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for tic_tac_toe from the source code\&.
